### ISSUE TITLE
set: Unknown option “-a”

### ISSUE THREAD

**Issue by foxcpp** [0ion9/fish_tmsu#1]
```
> tmsu set: Unknown option “-a”
~/.config/fish/completions/tmsu.fish (line 385): 
set -a conf fileFingerprintAlgorithm{,=none,={dynamic:,}{SHA{1,256},MD5}} symlinkFingerprintAlgorithm{,={none,follow,targetName{,NoExt}}}
^
from sourcing file ~/.config/fish/completions/tmsu.fish
	called on standard input

in command substitution
	called on standard input
...
```

### Steps to reproduce
1. Install fish_tmsu (copy directories to `~/.config/fish`)
2. Launch new shell
3. Type `tmsu `
4. Press Tab to trigger completion

### Additional information
```
fish, version 2.7.1
```

Looks like `set -a` is available since fish 3.0 (not yet released).

**Comment by 0ion9** [comment]
Thanks for your bug report.

Yeah, I was aware of this. Hoped I wouldn't have to change because `set $foo [..]` is less obvious in meaning than `set -a foo [..]`.

I've pushed an update which should fix this.
